const VEHICULOS_EXCEL = [
  { codigo: "001", marca: "Renault", modelo: "Duster" },
  { codigo: "002", marca: "Renault", modelo: "Kwid" },
  { codigo: "003", marca: "Renault", modelo: "Logan" },
  { codigo: "004", marca: "Renault", modelo: "Sandero" },
  { codigo: "005", marca: "Renault", modelo: "Stepway" },
  { codigo: "006", marca: "Renault", modelo: "Captur" },
  { codigo: "007", marca: "Renault", modelo: "Koleos" },
  { codigo: "008", marca: "Renault", modelo: "Arkana" },
  { codigo: "009", marca: "Renault", modelo: "Clio" },
  { codigo: "010", marca: "Renault", modelo: "Megane" },
  { codigo: "011", marca: "Renault", modelo: "Fluence" },

  { codigo: "012", marca: "Chevrolet", modelo: "Onix" },
  { codigo: "013", marca: "Chevrolet", modelo: "Sail" },
  { codigo: "014", marca: "Chevrolet", modelo: "Tracker" },
  { codigo: "015", marca: "Chevrolet", modelo: "Spark" },
  { codigo: "016", marca: "Chevrolet", modelo: "Captiva" },
  { codigo: "017", marca: "Chevrolet", modelo: "Colorado" },
  { codigo: "018", marca: "Chevrolet", modelo: "Cruze" },
  { codigo: "019", marca: "Chevrolet", modelo: "Aveo" },
  { codigo: "020", marca: "Chevrolet", modelo: "Tahoe" },
  { codigo: "021", marca: "Chevrolet", modelo: "Blazer" },
  { codigo: "022", marca: "Chevrolet", modelo: "Equinox" },

  { codigo: "023", marca: "Mazda", modelo: "CX-3" },
  { codigo: "024", marca: "Mazda", modelo: "CX-5" },
  { codigo: "025", marca: "Mazda", modelo: "CX-30" },
  { codigo: "026", marca: "Mazda", modelo: "Mazda 2" },
  { codigo: "027", marca: "Mazda", modelo: "Mazda 3" },
  { codigo: "028", marca: "Mazda", modelo: "BT-50" },
  { codigo: "029", marca: "Mazda", modelo: "CX-9" },
  { codigo: "030", marca: "Mazda", modelo: "MX-5" },
  { codigo: "031", marca: "Mazda", modelo: "626" },
  { codigo: "032", marca: "Mazda", modelo: "RX-8" },
  { codigo: "033", marca: "Mazda", modelo: "Mazda 6" },

  { codigo: "034", marca: "Toyota", modelo: "Corolla" },
  { codigo: "035", marca: "Toyota", modelo: "Hilux" },
  { codigo: "036", marca: "Toyota", modelo: "Fortuner" },
  { codigo: "037", marca: "Toyota", modelo: "Yaris" },
  { codigo: "038", marca: "Toyota", modelo: "Prado" },
  { codigo: "039", marca: "Toyota", modelo: "Land Cruiser" },
  { codigo: "040", marca: "Toyota", modelo: "Raize" },
  { codigo: "041", marca: "Toyota", modelo: "Rush" },
  { codigo: "042", marca: "Toyota", modelo: "Avanza" },
  { codigo: "043", marca: "Toyota", modelo: "4Runner" },
  { codigo: "044", marca: "Toyota", modelo: "Supra" },

  { codigo: "045", marca: "Kia", modelo: "Sportage" },
  { codigo: "046", marca: "Kia", modelo: "Rio" },
  { codigo: "047", marca: "Kia", modelo: "Picanto" },
  { codigo: "048", marca: "Kia", modelo: "Cerato" },
  { codigo: "049", marca: "Kia", modelo: "Seltos" },
  { codigo: "050", marca: "Kia", modelo: "Sorento" },
  { codigo: "051", marca: "Kia", modelo: "Soul" },
  { codigo: "052", marca: "Kia", modelo: "Stinger" },
  { codigo: "053", marca: "Kia", modelo: "Carnival" },
  { codigo: "054", marca: "Kia", modelo: "Niro" },
  { codigo: "055", marca: "Kia", modelo: "Optima" },

  { codigo: "056", marca: "Hyundai", modelo: "Tucson" },
  { codigo: "057", marca: "Hyundai", modelo: "Accent" },
  { codigo: "058", marca: "Hyundai", modelo: "Elantra" },
  { codigo: "059", marca: "Hyundai", modelo: "Santa Fe" },
  { codigo: "060", marca: "Hyundai", modelo: "Creta" },
  { codigo: "061", marca: "Hyundai", modelo: "i10" },
  { codigo: "062", marca: "Hyundai", modelo: "i20" },
  { codigo: "063", marca: "Hyundai", modelo: "Kona" },
  { codigo: "064", marca: "Hyundai", modelo: "Palisade" },
  { codigo: "065", marca: "Hyundai", modelo: "Veloster" },
  { codigo: "066", marca: "Hyundai", modelo: "Sonata" },

  { codigo: "067", marca: "Nissan", modelo: "Versa" },
  { codigo: "068", marca: "Nissan", modelo: "Sentra" },
  { codigo: "069", marca: "Nissan", modelo: "Kicks" },
  { codigo: "070", marca: "Nissan", modelo: "Frontier" },
  { codigo: "071", marca: "Nissan", modelo: "X-Trail" },
  { codigo: "072", marca: "Nissan", modelo: "March" },
  { codigo: "073", marca: "Nissan", modelo: "Altima" },
  { codigo: "074", marca: "Nissan", modelo: "Pathfinder" },
  { codigo: "075", marca: "Nissan", modelo: "Rogue" },
  { codigo: "076", marca: "Nissan", modelo: "Murano" },
  { codigo: "077", marca: "Nissan", modelo: "370Z" },

  { codigo: "078", marca: "Volkswagen", modelo: "Jetta" },
  { codigo: "079", marca: "Volkswagen", modelo: "Gol" },
  { codigo: "080", marca: "Volkswagen", modelo: "Polo" },
  { codigo: "081", marca: "Volkswagen", modelo: "T-Cross" },
  { codigo: "082", marca: "Volkswagen", modelo: "Tiguan" },
  { codigo: "083", marca: "Volkswagen", modelo: "Amarok" },
  { codigo: "084", marca: "Volkswagen", modelo: "Passat" },
  { codigo: "085", marca: "Volkswagen", modelo: "Golf" },
  { codigo: "086", marca: "Volkswagen", modelo: "Virtus" },
  { codigo: "087", marca: "Volkswagen", modelo: "Taos" },
  { codigo: "088", marca: "Volkswagen", modelo: "Beetle" },

  { codigo: "089", marca: "Ford", modelo: "EcoSport" },
  { codigo: "090", marca: "Ford", modelo: "Ranger" },
  { codigo: "091", marca: "Ford", modelo: "Explorer" },
  { codigo: "092", marca: "Ford", modelo: "Escape" },
  { codigo: "093", marca: "Ford", modelo: "F-150" },
  { codigo: "094", marca: "Ford", modelo: "Mustang" },
  { codigo: "095", marca: "Ford", modelo: "Edge" },
  { codigo: "096", marca: "Ford", modelo: "Bronco" },
  { codigo: "097", marca: "Ford", modelo: "Fusion" },
  { codigo: "098", marca: "Ford", modelo: "Expedition" },
  { codigo: "099", marca: "Ford", modelo: "Fiesta" },

  { codigo: "100", marca: "Suzuki", modelo: "Vitara" },
  { codigo: "101", marca: "Suzuki", modelo: "Swift" },
  { codigo: "102", marca: "Suzuki", modelo: "Jimny" },
  { codigo: "103", marca: "Suzuki", modelo: "Ertiga" },
  { codigo: "104", marca: "Suzuki", modelo: "Baleno" },
  { codigo: "105", marca: "Suzuki", modelo: "S-Cross" },
  { codigo: "106", marca: "Suzuki", modelo: "Celerio" },
  { codigo: "107", marca: "Suzuki", modelo: "XL7" },
  { codigo: "108", marca: "Suzuki", modelo: "Alto" },
  { codigo: "109", marca: "Suzuki", modelo: "Ignis" },
  { codigo: "110", marca: "Suzuki", modelo: "Grand Vitara" }
];